### ISSUE TITLE
NameError: name 'tf_model_class' is not defined

### ISSUE THREAD

**Issue by builtfordeve** [yg211/bert_nli#9]
2020-12-11 19:57:14 - Lock 140474735309264 acquired on /Users/mac/.cache/torch/transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157.lock
2020-12-11 19:57:14 - https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin not found in cache or force_download set to True, downloading to /Users/mac/.cache/torch/transformers/tmp_34x9lwo
Downloading: 100%|██████████| 440M/440M [3:20:47<00:00, 36.6kB/s]
Traceback (most recent call last):
  File "/Users/mac/Downloads/bert_nli-master/train.py", line 181, in <module>
    model = BertNLIModel(gpu=gpu, batch_size=batch_size, bert_type=bert_type, model_path=trained_model, reinit_num=reinit_layers, freeze_layers=freeze_layers)
2020-12-11 23:18:04 - storing https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin in cache at /Users/mac/.cache/torch/transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
  File "/Users/mac/Downloads/bert_nli-master/bert_nli.py", line 21, in __init__
    self.bert = BertModel.from_pretrained('bert-base-uncased')
2020-12-11 23:18:04 - creating metadata file for /Users/mac/.cache/torch/transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
  File "/Users/mac/miniconda3/envs/test_py3/lib/python3.6/site-packages/transformers/modeling_utils.py", line 536, in from_pretrained
    model = load_tf2_checkpoint_in_pytorch_model(model, resolved_archive_file, allow_missing_keys=True)
2020-12-11 23:18:04 - Lock 140474735309264 released on /Users/mac/.cache/torch/transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157.lock
  File "/Users/mac/miniconda3/envs/test_py3/lib/python3.6/site-packages/transformers/modeling_tf_pytorch_utils.py", line 227, in load_tf2_checkpoint_in_pytorch_model
    tf_model = tf_model_class(pt_model.config)
NameError: name 'tf_model_class' is not defined
2020-12-11 23:18:04 - loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin from cache at /Users/mac/.cache/torch/transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
2020-12-11 23:18:05 - Loading TensorFlow weights from /Users/mac/.cache/torch/transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157

Process finished with exit code 1
I wanna know how can I solve this problem? I have been downloaded the pre-trained model,but name tf_model_class is not defined.Please help me!

**Comment by builtfordeve** [comment]
I solved the problem before. I added a line of code : tf_model_class = getattr(transformers, tf_model_class_name).
I think my package transformers has some wrong. Because there is a new problem:
Traceback (most recent call last):
  File "/Users/mac/Downloads/bert_nli-master/example.py", line 5, in <module>
    model = BertNLIModel('output/{}.state_dict'.format(bert_type), bert_type=bert_type)
  File "/Users/mac/Downloads/bert_nli-master/bert_nli.py", line 21, in __init__
    self.bert = BertModel.from_pretrained('bert-base-uncased')
  File "/Users/mac/miniconda3/envs/test_py3/lib/python3.6/site-packages/transformers/modeling_utils.py", line 536, in from_pretrained
    model = load_tf2_checkpoint_in_pytorch_model(model, resolved_archive_file, allow_missing_keys=True)
  File "/Users/mac/miniconda3/envs/test_py3/lib/python3.6/site-packages/transformers/modeling_tf_pytorch_utils.py", line 227, in load_tf2_checkpoint_in_pytorch_model
    tf_model_class = getattr(transformers, tf_model_class_name)
AttributeError: module 'transformers' has no attribute 'TFBertModel'
Please give me some suggestions! Thanks~

**Comment by builtfordeve** [comment]
I update my transformers and solved that problem.But new one is coming:
=====Arguments=====
Traceback (most recent call last):
bert type:	bert-base
trained model path:	None
batch size:	8
  File "/Users/mac/Downloads/bert_nli-master/train.py", line 152, in <module>
epoch num:	1
fp16:	False
check_point:	False
gpu:	True
    logging.basicConfig(format='%(asctime)s - %(message)s',
scheduler setting:	WarmupLinear
max grad norm:	1.0
warmup percent:	0.2
using hans:	False
AttributeError: module 'transformers.utils.logging' has no attribute 'basicConfig'
=====Arguments=====
model save path output/nli_bert-base-2020-12-12_12-00-40

**Comment by builtfordeve** [comment]
I solved all problems but one, AssertionError: Torch not compiled with CUDA enabled.
Is that my Mac problem?

**Comment by yg211** [comment]
Right, I suspect your Mac does not have an nvidia GPU card, so the error arises because the code, by default, attempts to run with GPU acceleration. To solve this problem, pass argument --gpu 0 when you run the code; that will enforce the code to only use CPUs to run.

**Comment by builtfordeve** [comment]
Thank you for your replying. I change 1 to 0 and it worked. You are a nice guy!



发自我的iPhone


------------------ Original ------------------
